on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        # Build and push your Docker image
        docker build -t tdaproj:dev -p 443 .
        docker push tdaproj:dev

    - name: Deploy to Tour-de-App
      uses: Tour-de-App/deploy-action@v1
      with:
        image: tdaproj:dev
        name: tdaproj:dev
        team_secret: 55b6d716b77bc555e5550c8da1eb0839